# Generated by Django 4.2.19 on 2025-02-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='app_name',
            field=models.CharField(choices=[('core.apps.CoreConfig', 'core.apps.CoreConfig'), ('cheat_sql.apps.CheatSqlConfig', 'cheat_sql.apps.CheatSqlConfig'), ('django_bootstrap5', 'django_bootstrap5')], default='core.apps.CoreConfig', max_length=50),
        ),
    ]
