# Generated by Django 4.2.19 on 2025-02-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_course_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='app_name',
            field=models.CharField(choices=[('core', 'core'), ('cheat_sql', 'cheat_sql'), ('cheat_py', 'cheat_py')], default='core', max_length=50),
        ),
    ]
