# Generated by Django 4.2.19 on 2025-02-28 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=200, unique=True)),
                ('chapter_description', models.TextField()),
                ('published', models.BooleanField(default=False)),
                ('chapter_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Clauses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_name', models.CharField(max_length=200)),
                ('db', models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('mssql', 'MS SQL Server'), ('oracle', 'Oracle'), ('all', 'All')], default='all', max_length=20)),
                ('variant', models.CharField(choices=[('gernaral_sql', 'General SQL'), ('pl_sql', 'PL/SQL'), ('transact_sql', 'Transact-SQL'), ('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('mssql', 'MS SQL Server'), ('oracle', 'Oracle')], default='gernaral_sql', max_length=20)),
                ('clause_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=200)),
                ('lesson_type', models.CharField(choices=[('lab', 'Lab'), ('lecture', 'Lecture'), ('quiz', 'Quiz')], default='lecture', max_length=20)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('lesson_description', models.TextField()),
                ('published', models.BooleanField(default=False)),
                ('lesson_date', models.DateTimeField(verbose_name='date published')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheat_sql.chapter')),
                ('lesson_clauses', models.ManyToManyField(to='cheat_sql.clauses')),
            ],
        ),
    ]
