# Generated by Django 4.2.19 on 2025-03-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheat_sql', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='lessons_image/')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='text_content',
            field=models.FileField(blank=True, upload_to='lessons_text/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='images',
            field=models.ManyToManyField(to='cheat_sql.images'),
        ),
    ]
