# Generated by Django 4.2.19 on 2025-03-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheat_sql', '0002_images_lesson_text_content_lesson_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.CharField(choices=[('sql', 'SQL'), ('python', 'Python')], default='sql', max_length=20),
        ),
    ]
