# Generated by Django 4.2.19 on 2025-03-03 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheat_sql', '0003_chapter_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clauses',
            new_name='Clause',
        ),
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
