# Generated by Django 4.2.19 on 2025-03-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheat_sql', '0004_rename_clauses_clause_rename_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_clauses',
            field=models.ManyToManyField(blank=True, null=True, to='cheat_sql.clause'),
        ),
    ]
