# Generated by Django 4.2.19 on 2025-03-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheat_sql', '0007_chapter_chapter_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='slug',
            field=models.SlugField(default='slug4886051740534', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_number',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(default='slug277178188424850003110436104', max_length=200, unique=True),
        ),
    ]
