# Generated by Django 4.2.19 on 2025-03-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheat_sql', '0008_chapter_slug_lesson_lesson_number_lesson_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='slug',
            field=models.SlugField(default='slug2679057287051', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(default='slug728382024409328666736570478', max_length=200, unique=True),
        ),
    ]
